version: '2'
services:
  moveit-demo:
    image: gramaziokohler/ros-noetic-moveit
    container_name: moveit-demo
    environment:
      - ROS_HOSTNAME=moveit-demo
      - ROS_MASTER_URI=http://ros-core:11311
      # GUI Option 1: To forward the GUI to an external X11 server (eg. XMing), uncomment the following line
      # - DISPLAY=host.docker.internal:0.0
      # GUI Option 2: To use the web-based GUI, uncomment the following line
      # - DISPLAY=gui:0.0
    depends_on:
      - ros-core
      # To use the web-based GUI, uncomment the following line
      # - gui
    command:
      - roslaunch
      - --wait
      # To change the robot, select the corresponding package name here, eg. `ur10e_moveit_config`
      - abb_irb1600_6_12_moveit_config
      - demo.launch
      # To launch the RVIZ GUI, change the following to true and activate one of the two GUI options above
      - use_rviz:=false

  ros-core:
    image: gramaziokohler/ros-noetic-moveit
    container_name: ros-core
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: gramaziokohler/ros-noetic-moveit
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-core:11311"
    ports:
      - "9090:9090"
    depends_on:
      - ros-core
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch

  ros-fileserver:
    image: gramaziokohler/ros-noetic-moveit
    container_name: ros-fileserver
    environment:
      - ROS_HOSTNAME=ros-fileserver
      - ROS_MASTER_URI=http://ros-core:11311
    depends_on:
      - ros-core
    command:
      - roslaunch
      - --wait
      - file_server
      - file_server.launch

  # To use the web-based GUI, uncomment the following lines
  # gui:
  #   image: gramaziokohler/novnc:latest
  #   ports:
  #     - "8080:8080"
